/* Conventional Commits + cz-git prompts (emoji labels for `npm run commit`). */
/** @type {import('@commitlint/types').UserConfig} */
export default {
  extends: ["@commitlint/config-conventional"],
  rules: {
    // No max length on header / body / footer (team preference; avoid wizard + commitlint fighting).
    "header-max-length": [0],
    "body-max-line-length": [0],
    "footer-max-line-length": [0],
    // Allow subjects ending with `.` (long / sentence-style subjects from cz-git).
    "subject-full-stop": [0],
  },
  /* cz-git reads `prompt` from this file when using `npm run commit` */
  prompt: {
    alias: { fd: "docs: fix typos" },
    /* Scopes mirror internal-docs/ARCHITECTURE.md (packages) + PRD waves / monorepo layout. */
    scopes: [
      {
        value: "core",
        name: "core — @better-seo/core (model, merge, JSON-LD, validate, registry)",
      },
      { value: "next", name: "next — @better-seo/next (Metadata, seo(), NextJsonLd)" },
      { value: "react", name: "react — @better-seo/react (Helmet / SPA, planned)" },
      { value: "assets", name: "assets — @better-seo/assets (OG PNG, icons, PWA manifest)" },
      { value: "cli", name: "cli — @better-seo/cli (better-seo / better-seo-cli bins)" },
      { value: "remix", name: "remix — @better-seo/remix adapter (planned)" },
      { value: "astro", name: "astro — @better-seo/astro adapter (planned)" },
      { value: "nuxt", name: "nuxt — @better-seo/nuxt adapter (planned)" },
      { value: "crawl", name: "crawl — @better-seo/crawl (sitemap/robots, planned)" },
      { value: "examples-next", name: "examples-next — examples/nextjs-app (N10 E2E)" },
      { value: "examples-vanilla", name: "examples-vanilla — examples/vanilla-render-tags" },
      { value: "examples-react-vite", name: "examples-react-vite — examples/react-seo-vite" },
      { value: "docs", name: "docs — docs/ recipes & public stubs" },
      { value: "internal-docs", name: "internal-docs — PRD, ARCHITECTURE, FEATURES, Roadmap" },
      { value: "repo", name: "repo — root package.json, tsconfig, scripts, workspaces" },
      { value: "ci", name: "ci — .github/workflows, Actions" },
      { value: "changesets", name: "changesets — .changeset, release.yml integration" },
    ],
    messages: {
      type: "Select the type of change:",
      scope: "Scope (affected area — pick package, example, or infra):",
      subject: "Short description:\n",
      body: 'Longer description (optional). Use "|" for new line:\n',
      breaking: "List BREAKING CHANGES (optional):\n",
      footerPrefixSelect: "Footer prefix (optional):",
      customFooterPrefix: "Custom footer prefix:",
      footer: "Footer (optional, e.g. issues):\n",
      confirmCommit: "Look good?",
    },
    types: [
      { value: "feat", name: "feat:     ✨ New feature", emoji: ":sparkles:" },
      { value: "fix", name: "fix:      🐛 Bug fix", emoji: ":bug:" },
      { value: "docs", name: "docs:     📝 Documentation", emoji: ":memo:" },
      { value: "style", name: "style:    💄 Format / no code change", emoji: ":lipstick:" },
      { value: "refactor", name: "refactor: ♻️  Refactor", emoji: ":recycle:" },
      { value: "perf", name: "perf:     ⚡ Performance", emoji: ":zap:" },
      { value: "test", name: "test:     ✅ Tests", emoji: ":white_check_mark:" },
      { value: "build", name: "build:    📦 Build / tooling", emoji: ":package:" },
      { value: "ci", name: "ci:       👷 CI", emoji: ":construction_worker:" },
      { value: "chore", name: "chore:    🔧 Chore / misc", emoji: ":wrench:" },
      { value: "revert", name: "revert:   ⏪ Revert", emoji: ":rewind:" },
    ],
    useEmoji: true,
    emojiAlign: "center",
    allowCustomScopes: true,
    allowEmptyScopes: true,
    emptyScopesAlias: "empty",
    customScopesAlign: "bottom",
    defaultScope: "",
    customScopesAlias: "custom",
    upperCaseSubject: false,
    allowBreakingChanges: ["feat", "fix"],
    breaklineChar: "|",
    skipQuestions: [],
    issuePrefixes: [{ value: "closes", name: "closes:   Closing issues" }],
    customIssuePrefixAlign: "top",
    emptyIssuePrefixAlias: "skip",
    customIssuePrefixAlias: "custom",
    allowCustomIssuePrefix: true,
    confirmColorize: true,
    maxHeaderLength: Number.MAX_SAFE_INTEGER,
    maxSubjectLength: Number.MAX_SAFE_INTEGER,
    minSubjectLength: 0,
    scopeOverrides: undefined,
    defaultIssues: "",
    defaultBody: "",
  },
}
